version: '3.8'

networks:
  rede_microsservicos:
    external: true

services:
  db:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.2

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doxito007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.3
    depends_on:
      - db

  controller-cadastro-autenticacao:
    image: jonasrsribeiro/lw-controller-cadastro-autenticacao:develop
    ports:
      - "3000:3000"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.4
    depends_on:
      - pgadmin

  mysql:
    build: .
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estacoes_parametros_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.5

  controller-gerenciamento-estacoes-metricas:
    image: jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:develop
    ports:
      - "3001:3001"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.6
    depends_on:
      - mysql

  frontend:
    image: jonasrsribeiro/lw-frontend:develop
    ports:
      - "5000:5000"
    volumes:
      - front-data:/app
    environment:
      - NODE_ENV=development
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.7
    depends_on:
      - db
      - mysql
      - controller-cadastro-autenticacao
      - controller-gerenciamento-estacoes-metricas

  controller-recepcao-dados:
    image: jonasrsribeiro/lw-controller-recepcao-dados:develop
    ports:
      - "3002:3002"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.8
    depends_on:
      - db
      - mysql
      - controller-cadastro-autenticacao
      - controller-gerenciamento-estacoes-metricas
      - frontend

  controller-tratamento-dados:
    image: jonasrsribeiro/lw-controller-tratamento-dados:develop
    ports:
      - "3003:3003"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.9
    depends_on:
      - db
      - mysql
      - controller-cadastro-autenticacao
      - controller-gerenciamento-estacoes-metricas
      - frontend
      - controller-recepcao-dados

volumes:
  postgres-data:
  mysql-data:
  front-data: