name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

      - name: Build and tag Docker image for Development
        run: |
          docker build -t jonasrsribeiro/lw-controller-tratamento-dados -f Dockerfile.dev .
          docker tag jonasrsribeiro/lw-controller-tratamento-dados:latest jonasrsribeiro/lw-controller-tratamento-dados:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-tratamento-dados:latest
          docker push jonasrsribeiro/lw-controller-tratamento-dados:develop