name: staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

      - name: Merge to prod
        if: success() && github.ref == 'refs/heads/staging'
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |
          git config user.name "jonasrsribeiro"
          git config user.email "jonas.ribeiro01@fatec.sp.gov.br"
          git fetch origin
          git checkout staging
          git pull origin staging
          git checkout prod
          git merge --allow-unrelated-histories --strategy-option=theirs staging
          git push origin prod
